import { deriveBrandColors } from './colors'
import type { IntakeData } from './types'

// Escape a string for use inside a JS template literal
function esc(s: string): string {
  return s.replace(/\\/g, '\\\\').replace(/`/g, '\\`').replace(/\$/g, '\\$')
}

// Truncate to max length at a word boundary
function truncate(s: string, max: number): string {
  if (s.length <= max) return s
  const cut = s.slice(0, max)
  const last = cut.lastIndexOf(' ')
  return (last > 0 ? cut.slice(0, last) : cut).replace(/[.,;:!?-]+$/, '')
}

function deriveCtaLabel(payload: IntakeData): string {
  if (payload.phoneReliability === 'Strong') return 'Call Now'
  if (payload.schedulingMethod === 'Embedded booking widget') return 'Schedule Appointment'
  if (payload.schedulingMethod === 'External booking URL') return 'Schedule Appointment'
  return 'Request Appointment'
}

function deriveBookingUrl(payload: IntakeData): string {
  if (payload.schedulingMethod === 'Contact form only') return '/contact'
  return '/book'
}

function formatPhoneTel(phone: string): string {
  const digits = phone.replace(/\D/g, '')
  if (digits.length === 10) return `tel:+1${digits}`
  if (digits.length === 11 && digits[0] === '1') return `tel:+${digits}`
  return digits ? `tel:${digits}` : ''
}

// ---------------------------------------------------------------------------
// 1. src/config/site.ts
// ---------------------------------------------------------------------------

export function generateSiteConfig(slug: string, payload: IntakeData): string {
  const manufacturers = [
    ...payload.featuredManufacturers,
    ...payload.manufacturersCarried.filter(m => !payload.featuredManufacturers.includes(m)),
  ]

  const locations = payload.locations.length > 0
    ? payload.locations.map(loc => ({
        name: loc.name || payload.businessName,
        address: loc.address,
        city: loc.city,
        state: loc.state,
        zip: loc.zip,
        phone: loc.phone,
        phoneTel: formatPhoneTel(loc.phone),
      }))
    : [{
        name: payload.businessName,
        address: '',
        city: payload.serviceArea,
        state: '',
        zip: '',
        phone: payload.primaryPhone,
        phoneTel: formatPhoneTel(payload.primaryPhone),
      }]

  const teamMembers = payload.teamMembers.map(m => ({
    name: m.name,
    title: m.title,
    credentials: m.credentials,
  }))

  const metaDesc = truncate(
    `${payload.businessName} provides ${payload.primaryServices || 'comprehensive hearing care'} in ${payload.serviceArea || 'your area'}. Schedule your appointment today.`,
    160
  )

  const tagline = payload.serviceArea
    ? `Expert ${payload.practiceType || 'Hearing Care'} in ${payload.serviceArea}`
    : `Expert ${payload.practiceType || 'Hearing Care'}`

  const config = {
    business: {
      name: payload.businessName,
      slug,
      tagline,
      foundedYear: null,
      yearsInBusiness: '',
      reviewCount: '100+',
      reviewRating: '5.0',
    },
    contact: {
      primaryPhone: payload.primaryPhone,
      primaryPhoneTel: formatPhoneTel(payload.primaryPhone),
      primaryEmail: payload.domain ? `info@${payload.domain}` : '',
      bookingUrl: deriveBookingUrl(payload),
      bookingCtaLabel: deriveCtaLabel(payload),
    },
    seo: {
      siteUrl: payload.domain ? `https://${payload.domain}` : '',
      defaultMetaDescription: metaDesc,
    },
    locations,
    manufacturers,
    teamMembers,
    insurancePartners: [],
    nav: [
      { label: 'Hearing Aids', href: '/hearing-aids' },
      { label: 'Hearing Tests', href: '/hearing-tests' },
      { label: 'Our Team', href: '/our-team' },
      { label: 'Services', href: '/services' },
      { label: 'Contact', href: '/contact' },
    ],
  }

  return `// Auto-generated by ELM Pipeline Stage 2
// Client: ${esc(payload.businessName)}
// Generated: ${new Date().toISOString()}

const siteConfig = ${JSON.stringify(config, null, 2)} as const

export default siteConfig
`
}

// ---------------------------------------------------------------------------
// 2. src/index.css
// ---------------------------------------------------------------------------

export function generateIndexCss(payload: IntakeData): string {
  const colors = deriveBrandColors(payload.primaryBrandColor)

  return `@import "tailwindcss";

@theme {
  --color-brand-primary: ${colors.primary};
  --color-brand-secondary: ${colors.secondary};
  --color-brand-accent: ${colors.accent};
  --color-brand-cream: ${colors.cream};
}
`
}

// ---------------------------------------------------------------------------
// 3. src/config/redirects.ts
// ---------------------------------------------------------------------------

export function generateRedirects(payload: IntakeData): string {
  // Best-effort: extract redirect-looking lines from contentToKeep
  const redirects: Record<string, string> = {}

  if (payload.contentToKeep) {
    const lines = payload.contentToKeep.split('\n')
    for (const line of lines) {
      // Match patterns like "/old-path -> /new-path" or "/old-path => /new-path"
      const match = line.trim().match(/^(\/\S+)\s*(?:->|=>|→)\s*(\/\S+)/)
      if (match) {
        redirects[match[1]] = match[2]
      }
    }
  }

  if (Object.keys(redirects).length === 0) {
    return `// Auto-generated by ELM Pipeline Stage 2
// No redirects extracted from intake. Add manually if needed.

export const REDIRECTS: Record<string, string> = {}
`
  }

  return `// Auto-generated by ELM Pipeline Stage 2

export const REDIRECTS: Record<string, string> = ${JSON.stringify(redirects, null, 2)}
`
}

// ---------------------------------------------------------------------------
// 4. src/pages/Book.tsx
// ---------------------------------------------------------------------------

export function generateBookPage(payload: IntakeData): string {
  if (payload.schedulingMethod === 'Embedded booking widget' && payload.bookingIframeCode) {
    // Extract src from iframe tag if present, otherwise use raw code
    const srcMatch = payload.bookingIframeCode.match(/src=["']([^"']+)["']/)
    const iframeSrc = srcMatch ? srcMatch[1] : null

    if (iframeSrc) {
      return `// Auto-generated by ELM Pipeline Stage 2 — Embedded booking widget

export default function BookPage() {
  return (
    <div className="min-h-screen bg-brand-cream">
      <div className="max-w-4xl mx-auto px-4 py-16">
        <h1 className="text-3xl font-bold text-gray-900 mb-2">Schedule Your Appointment</h1>
        <p className="text-gray-600 mb-8">
          Book your hearing consultation online. Choose a time that works best for you.
        </p>
        <div className="bg-white rounded-2xl shadow-sm border border-gray-100 overflow-hidden">
          <iframe
            src="${esc(iframeSrc)}"
            title="Schedule Appointment"
            className="w-full border-0"
            style={{ minHeight: '700px' }}
            allow="payment"
          />
        </div>
      </div>
    </div>
  )
}
`
    }

    // Raw embed code — render in a container
    return `// Auto-generated by ELM Pipeline Stage 2 — Embedded booking widget (raw embed)

export default function BookPage() {
  return (
    <div className="min-h-screen bg-brand-cream">
      <div className="max-w-4xl mx-auto px-4 py-16">
        <h1 className="text-3xl font-bold text-gray-900 mb-2">Schedule Your Appointment</h1>
        <p className="text-gray-600 mb-8">
          Book your hearing consultation online. Choose a time that works best for you.
        </p>
        <div
          className="bg-white rounded-2xl shadow-sm border border-gray-100 overflow-hidden p-6"
          dangerouslySetInnerHTML={{ __html: ${JSON.stringify(payload.bookingIframeCode)} }}
        />
      </div>
    </div>
  )
}
`
  }

  if (payload.schedulingMethod === 'External booking URL') {
    const bookingUrl = payload.bookingIframeCode || payload.scannedUrl || '#'
    return `// Auto-generated by ELM Pipeline Stage 2 — External booking URL

export default function BookPage() {
  return (
    <div className="min-h-screen bg-brand-cream">
      <div className="max-w-2xl mx-auto px-4 py-16 text-center">
        <h1 className="text-3xl font-bold text-gray-900 mb-4">Schedule Your Appointment</h1>
        <p className="text-gray-600 mb-8">
          Click below to schedule your hearing consultation through our online booking system.
        </p>
        <a
          href="${esc(bookingUrl)}"
          target="_blank"
          rel="noopener noreferrer"
          className="inline-block bg-brand-primary hover:opacity-90 text-white font-semibold py-4 px-8 rounded-xl transition-opacity text-lg"
        >
          Schedule Appointment
        </a>
      </div>
    </div>
  )
}
`
  }

  // Contact form only (default)
  return `// Auto-generated by ELM Pipeline Stage 2 — Contact form

export default function BookPage() {
  return (
    <div className="min-h-screen bg-brand-cream">
      <div className="max-w-2xl mx-auto px-4 py-16">
        <h1 className="text-3xl font-bold text-gray-900 mb-2">Request an Appointment</h1>
        <p className="text-gray-600 mb-8">
          Fill out the form below and we will contact you to schedule your hearing consultation.
        </p>
        <form className="space-y-4" action="/api/contact" method="POST">
          <div>
            <label className="block text-sm font-medium text-gray-700 mb-1">Full Name</label>
            <input
              type="text"
              name="name"
              required
              className="w-full border border-gray-300 rounded-xl px-4 py-3 text-gray-900 focus:border-brand-primary focus:outline-none"
            />
          </div>
          <div>
            <label className="block text-sm font-medium text-gray-700 mb-1">Email</label>
            <input
              type="email"
              name="email"
              required
              className="w-full border border-gray-300 rounded-xl px-4 py-3 text-gray-900 focus:border-brand-primary focus:outline-none"
            />
          </div>
          <div>
            <label className="block text-sm font-medium text-gray-700 mb-1">Phone</label>
            <input
              type="tel"
              name="phone"
              required
              className="w-full border border-gray-300 rounded-xl px-4 py-3 text-gray-900 focus:border-brand-primary focus:outline-none"
            />
          </div>
          <div>
            <label className="block text-sm font-medium text-gray-700 mb-1">Message</label>
            <textarea
              name="message"
              rows={4}
              className="w-full border border-gray-300 rounded-xl px-4 py-3 text-gray-900 focus:border-brand-primary focus:outline-none resize-y"
            />
          </div>
          <button
            type="submit"
            className="w-full bg-brand-primary hover:opacity-90 text-white font-semibold py-4 px-6 rounded-xl transition-opacity"
          >
            Request Appointment
          </button>
        </form>
      </div>
    </div>
  )
}
`
}
